# Generated by Django 2.1.3 on 2019-01-28 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190109_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='active_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='код подтверждения'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='active_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 17, 8, 46, 9, 323126, tzinfo=utc)),
        ),
    ]
