# Generated by Django 2.1.3 on 2019-01-28 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20190128_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='active_key',
            new_name='activation_key',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='active_key_expires',
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 17, 16, 34, 35, 399296, tzinfo=utc)),
        ),
    ]
